# Generated by Django 6.0.3 on 2026-03-27 17:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(choices=[('date_filter', 'Date Filter'), ('gender_filter', 'Gender Filter'), ('age_filter', 'Age Filter'), ('bar_chart_click', 'Bar Chart Click'), ('line_chart_click', 'Line Chart Click'), ('export_data', 'Export Data')], max_length=50, validators=[django.core.validators.MinLengthValidator(1)])),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Feature Click',
                'verbose_name_plural': 'Feature Clicks',
                'ordering': ['-timestamp'],
            },
        ),
    ]
