# Generated by Django 6.0.3 on 2026-03-27 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='featureclick',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_clicks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='featureclick',
            index=models.Index(fields=['user', 'timestamp'], name='analytics_f_user_id_243f29_idx'),
        ),
        migrations.AddIndex(
            model_name='featureclick',
            index=models.Index(fields=['feature_name', 'timestamp'], name='analytics_f_feature_97c23a_idx'),
        ),
    ]
